name: CI Tests

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  ubuntu:
    name: Test on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential python3-dev git

      - name: Install Python dependencies
        run: pip install pytest

      - name: Install package
        env:
          SETUPTOOLS_SCM_PRETEND_VERSION: 0.0.1
        run: pip install .

      - name: Run tests
        run: pytest tests/

  windows:
    name: Test on Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Visual Studio Build Tools
        shell: powershell
        run: |
          # Проверяем наличие Chocolatey
          if (-not (Get-Command choco -ErrorAction SilentlyContinue)) {
            Set-ExecutionPolicy Bypass -Scope Process -Force
            [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072
            iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
          }
          choco install visualstudio2022buildtools -y --package-parameters "--add Microsoft.VisualStudio.Workload.VCTools --includeRecommended"

      - name: Install Python dependencies
        run: pip install pytest

      - name: Install package
        env:
          SETUPTOOLS_SCM_PRETEND_VERSION: 0.0.1
        run: pip install .

      - name: Run tests
        run: pytest tests/

  arch:
    name: Test on Arch Linux
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
    steps:
      - uses: actions/checkout@v3

      - name: Install system dependencies
        run: |
          pacman -Syu --noconfirm base-devel git python python-pip

      - name: Set up virtual environment
        run: |
          python -m venv /opt/venv
          source /opt/venv/bin/activate
          pip install --upgrade pip

      - name: Install Python dependencies
        run: |
          source /opt/venv/bin/activate
          pip install pytest

      - name: Install package
        env:
          SETUPTOOLS_SCM_PRETEND_VERSION: 0.0.1
        run: |
          source /opt/venv/bin/activate
          pip install .

      - name: Run tests
        run: |
          source /opt/venv/bin/activate
          pytest tests/

  macos:
    name: Test on macOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install system dependencies
        run: |
          # Проверяем наличие Homebrew
          if ! command -v brew &> /dev/null; then
            /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          fi
          brew update

          # Устанавливаем Xcode Command Line Tools
          if ! xcode-select -p &> /dev/null; then
            sudo xcode-select --install
          fi

          brew install python3 git

      - name: Install Python dependencies
        run: pip install pytest

      - name: Install package
        env:
          SETUPTOOLS_SCM_PRETEND_VERSION: 0.0.1
        run: pip install .

      - name: Run tests
        run: pytest tests/
