name: CI Tests

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  ubuntu:

    name: Test on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: install pytest
        run: |
          pip install pytest
      - name: Run setup_all.py on Ubuntu
        run: |
          sudo python3 scripts/setup_all.py

      - name: Activate venv and run tests
        run: |
          pip install .
          pytest tests/

  windows:

    name: Test on Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: install pytest
        run: |
          pip install pytest
      - name: Run setup_all.py on Windows
        run: |
          python scripts/setup_all.py

      - name: Activate venv and run tests
        run: |
          pip install .
          pytest tests/

  arch:
    name: Test on Arch Linux (Docker)
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
    steps:
      - uses: actions/checkout@v3

      - name: Install system dependencies
        run: |
          pacman -Syu --noconfirm python python-pip git gcc

      - name: Set up virtual environment and install dependencies
        run: |
          python -m venv /opt/venv
          source /opt/venv/bin/activate
          python scripts/setup_all.py
          pip install --upgrade pip

      - name: Build and test local package
        run: |
          source /opt/venv/bin/activate
          pip install pytest
          pip install .
          pytest tests/

  macos:
    name: Test on macOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Run setup_all.py on macOS and setup pion
        run: |
          python3 scripts/setup_all.py
          pip install .
      - name: Activate venv and run tests
        run: |
          pip install pytest
          pytest tests/
