name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }} with ${{ matrix.python }} for ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python: [cp310, cp311, pp311]
        arch: [auto]
        include:
          - os: ubuntu-latest
            arch: arm64
          - os: macos-latest
            arch: auto
        exclude:
          - os: windows-latest
            python: pp311
          - os: windows-latest
            arch: arm64
          - os: macos-latest
            arch: arm64

    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        if: matrix.os == 'ubuntu-latest'
        uses: docker/setup-qemu-action@v3

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.23.2
        with:
          package-dir: .
          output-dir: wheelhouse
          config-file: "pyproject.toml"
          archs: ${{ matrix.arch }}

      - name: Build ARM wheels
        if: matrix.os == 'ubuntu-latest' && matrix.arch == 'arm64'
        run: |
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
          docker buildx create --use
          docker buildx build --platform=linux/arm64 -o type=local,dest=wheelhouse .

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ matrix.python }}-${{ matrix.arch }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl
