name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }} with ${{ matrix.python }} for ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python: [cp310, cp311, pp310]
        arch: [auto]
        include:
          - os: ubuntu-latest
            python: cp310
            arch: arm64
          - os: macos-latest
            arch: universal2
        exclude:
          - os: windows-latest
            python: pp310
          - os: windows-latest
            arch: arm64
          - os: macos-latest
            arch: arm64

    steps:
      - uses: actions/checkout@v4

      - name: Install ARM64 dependencies
        if: matrix.os == 'ubuntu-latest' && matrix.arch == 'arm64'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            gcc-aarch64-linux-gnu \
            g++-aarch64-linux-gnu \
            libopenblas-dev \
            liblapack-dev \
            gfortran \
            pkg-config
        env:
          CIBW_ARCHS: arm64
          NPY_USE_BLAS_ILP64: 1

      - name: Setup build tools
        uses: pypa/cibuildwheel@v2.23.2

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.23.2
        with:
          package-dir: .
          output-dir: wheelhouse
          config-file: "pyproject.toml"
          archs: ${{ matrix.arch }}
          platform: linux/arm64

      - uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}-${{ matrix.python }}
          path: ./wheelhouse/*.whl
