name: Build and Publish

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels for ${{ matrix.python }} on ${{ matrix.os }} (${{ matrix.arch }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          # Linux
          - os: ubuntu-latest
            python: cp313
            arch: x86_64
          - os: ubuntu-latest
            python: cp313
            arch: arm64
          - os: ubuntu-latest
            python: pp313
            arch: x86_64

          # macOS
          - os: macos-latest
            python: cp313
            arch: universal2

          # Windows
          - os: windows-latest
            python: cp313
            arch: x86_64

    steps:
      - uses: actions/checkout@v4

      - name: Install ARM64 dependencies
        if: matrix.os == 'ubuntu-latest' && matrix.arch == 'arm64'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libopenblas-dev \
            liblapack-dev \
            gfortran

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.23.2
        with:
          package-dir: .
          output-dir: wheelhouse
          config-file: "pyproject.toml"
          archs: ${{ matrix.arch }}

      - name: Upload wheels as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}-${{ matrix.python }}-${{ matrix.arch }}
          path: wheelhouse/*.whl

  publish:
    name: Publish wheels to PyPI
    needs: build_wheels
    runs-on: ubuntu-latest
    steps:
      - name: Download all wheel artifacts
        uses: actions/download-artifact@v4
        with:
          path: wheelhouse

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@v1.4.2
        with:
          packages_dir: wheelhouse
        env:
          PYPI_API_TOKEN: ${{ secrets.PYPI }}
